# Generated by Django 3.2.3 on 2021-07-11 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedAnomaly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('video', models.FileField(upload_to='videos')),
                ('frame1', models.ImageField(max_length=1000, null='true', upload_to='images')),
                ('frame2', models.ImageField(max_length=1000, null='true', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('video', models.FileField(upload_to='videos')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('username', models.CharField(default='Anonymous', max_length=30, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('picture', models.ImageField(default='media/images/defaultprofilepicture.png', max_length=1000, upload_to='images')),
                ('contact_no', models.CharField(max_length=11)),
                ('forget_password_token', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(blank=True, to='videos.Video')),
            ],
            options={
                'ordering': ['-username'],
            },
        ),
    ]
