# Generated by Django 2.2.18 on 2021-07-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedAnomaly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('video', models.FileField(upload_to='videos')),
                ('frame1', models.ImageField(max_length=1000, null='true', upload_to='images')),
                ('frame2', models.ImageField(max_length=1000, null='true', upload_to='images')),
            ],
        ),
    ]
